### ISSUE TITLE
Cannot close `mdxJsxFlowTag` with a particular resource

### ISSUE THREAD

**Issue by ttasovac** [DARIAH-ERIC/dariah-campus#261]
### Bug report

@stefanprobst when I merge https://github.com/DARIAH-ERIC/dariah-campus/pull/149 into the [elexis](https://github.com/DARIAH-ERIC/dariah-campus/tree/elexis) branch, I am getting this error on this particular resource (`how-to-publish-your-dictionary-data-with-publex`) 

```
Error: Cannot close `mdxJsxFlowTag` (308:3-308:14): a different token (`listItem`, 306:1-308:14) is open
    at Object.exit (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/mdast-util-from-markdown/dist/index.js:419:13)
    at Object.exitMdxJsxTag (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/mdast-util-mdx-jsx/from-markdown.js:224:10)
    at compile (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/mdast-util-from-markdown/dist/index.js:191:40)
    at fromMarkdown (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/mdast-util-from-markdown/dist/index.js:24:27)
    at parse (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/remark-parse/index.js:13:12)
    at Function.parse (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/unified/index.js:271:12)
    at pipelineParse (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/unified/index.js:23:16)
    at wrapped (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/trough/wrap.js:25:19)
    at next (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/trough/index.js:57:24)
    at Object.run (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/trough/index.js:31:10)
wait  - compiling...
event - compiled successfully
Error: Cannot close `mdxJsxFlowTag` (308:3-308:14): a different token (`listItem`, 306:1-308:14) is open
    at Object.exit (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/mdast-util-from-markdown/dist/index.js:419:13)
    at Object.exitMdxJsxTag (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/mdast-util-mdx-jsx/from-markdown.js:224:10)
    at compile (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/mdast-util-from-markdown/dist/index.js:191:40)
    at fromMarkdown (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/mdast-util-from-markdown/dist/index.js:24:27)
    at parse (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/remark-parse/index.js:13:12)
    at Function.parse (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/unified/index.js:271:12)
    at pipelineParse (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/unified/index.js:23:16)
    at wrapped (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/trough/wrap.js:25:19)
    at next (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/trough/index.js:57:24)
    at Object.run (/Users/ttasovac/Development/DARIAH/dariah-campus/node_modules/trough/index.js:31:10) 
```

This resource was created before the CMS was ready, so the Markdown structure is written by hand: it's fairly complex and a bit messy. 

I did manage to fix some formatting issues manually and got it to preview locally before committing and pushing, but `yarn format:fix ` breaks the resource again, which leads to the same prerender erros and hence a broken build on Vercel. 

I really don't know how to fix this. Can you please take a look?

All best,
Toma

**Comment by stefanprobst** [comment]
i did push to the PR branch, but after re-reading the issue i'm not sure if you want me to fix that in the elexis branch (which has the PR merged already) instead?

**Comment by stefanprobst** [comment]
also, as a sidenote: the mdx document uses lots of empty anchor tags as link targets - we should not do that.

**Comment by ttasovac** [comment]
Thanks a million, @stefanprobst! Don't worry about the branch —  I can mege it myself into the elexis branch. 

UPDATE: actually, I spoke too soon. I can't merge the PR directly into the elexis branch because of a conflict. Any chance you can do it for me?

Do in-resource links work without empty anchor tags, i.e. by simply referring to the `#heading-slugs` should I just get rid of them?

**Comment by ttasovac** [comment]
@stefanprobst I merged the pr into the elexis branch but I am still getting the mdxJsxFlowTag error on build, which now blocks my further work on the elexis branch. Could you please take a look at the elexis branch and see what's wrong. 

Also, please let me know what I should do about empty anchor tags, which you said we shouldn't use.

**Comment by stefanprobst** [comment]
> what I should do about empty anchor tags, which you said we shouldn't use.

preferably, link targets should be headings (because if there's a link to a section, it should probably also be listed in the table of contents). and for heading elements, we already generate ids, so we can just use those for in-page links.

**Comment by stefanprobst** [comment]
mdx issues are fixed, see https://elexis.humanistika.org/resource/posts/how-to-publish-your-dictionary-data-with-publex
